services:
  recipe_monitor:
    build:
      context: ./monitor_service
      dockerfile: Dockerfile
    container_name: recipe_monitor_app
    volumes:
      - /mnt/recipe_automation/data/input:/app/input # Incoming JPGs/PDFs
      - /mnt/recipe_automation/data/output:/app/output # Generated JSON files
      - /mnt/recipe_automation/data/archive:/app/archive # Processed original files
      - /mnt/recipe_automation/data/logs:/app/logs # Log files
    env_file:
      - .env # For API keys and other secrets
    depends_on:
      - web_ui
    restart: unless-stopped

  web_ui:
    build:
      context: ./web_ui_service
      dockerfile: Dockerfile
    container_name: recipe_web_ui
    ports:
      - "8000:8000" # Map container port 8000 to host port 8000
    volumes:
      - /mnt/recipe_automation/data/logs:/app/logs # Access logs from monitor service
    restart: unless-stopped

volumes:
  data:
  logs:
